name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image
      run: |-
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy webapp --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/webapp --region us-central1 --platform managed --allow-unauthenticated
